obj-$(CONFIG_NXP_NFC_I2C) := nfc_i2c.o

nfc_i2c-y := common.o \
             common_ese.o \
             i2c_drv.o

ifdef CONFIG_NXP_COLD_RESET
nfc_i2c-y += cold_reset.o
endif

nfc_i2c-y += nfc_vbat_monitor.o

ifdef CONFIG_DYNAMIC_DEBUG
ccflags-y += -DDYNAMIC_DEBUG_MODULE
endif

ifdef CONFIG_NXP_COLD_RESET
ccflags-y += -DCONFIG_NXP_COLD_RESET
endif

ccflags-y += -DCONFIG_NXP_NFC_VBAT_MONITOR
